In [4]:
from openai import OpenAI
from dotenv import load_dotenv
import os

In [3]:
load_dotenv()

True

In [10]:
client = OpenAI(
    api_key=os.environ.get("OPENAI_API_KEY"),
)

In [81]:
BASE_PROMPT = """\
You will be given a list of alerts used by the MTA to communicate delays. Your task is to determine what is the root \
cause of the delay in each case, along with the station that the issue occurred at or near.

Example input:
1. There will be delays between Chambers St and 14th St because of a train that had to be removed from the tracks due to a door \
problem near Houston St.
2. Southbound 4 trains are running with delays after EMS responded to a person in need of medical help at Crown Hts-Utica Av.
3. Expect delays on 2 trains because of a signal issue.

Desired reponse:
1. {issue: "Door problem", station: "Houston St"}
2. {issue: "Medical emergency", station: "Crown Hts-Utica Av"}
3. {issue: "Signal problem", station: "Unclear"}

The string used for the issue will be validated by an algorithm that expects one of the following strings:
["Door problem", "Rail problem", "Switch problem", "Signal problem", "Power problem", "Maintenance work", \
"Brakes activated", "Disruptive passenger", "Medical emergency", "Person on tracks", "Person struck by train", "Cleaning / vandalism", \
"Object on tracks", "Fire / smoke", "Unspecified FDNY", "South Channel Bridge open", "Assault", "Flooding", "Unknown mechanical problem", \
"Other"].
Do NOT provide an issue that is not in that list. The station name must be one of the 472 NYCT stations, or "Unclear", if there is ambiguity. 

Notes:
* Instead of Christopher St-Sheridan Sq, use Christopher St-Stonewall, since it has been recently renamed.

Here are the alerts:

"""

In [80]:
len(BASE_PROMPT)/4

379.5

In [82]:
INPUTS = '''\
1. Coney Island-bound F trains have resumed making local stops from Parsons Blvd to Kew Gardens - Union Tpke after our crews corrected a malfunctioning switch at Briarwood.
2. Canarsie-bound L trains are holding in stations while we remove a car in need of cleaning from service at Bedford Av.
3. Uptown A and C trains are delayed while NYPD responds to a disruptive passenger at 168 St.
4. Northbound 6 trains are delayed while our crews perform urgent track maintenance at Hunts Point Av.
5. Southbound 4 train service has resumed running local from Atlantic Av - Barclays Ctr to Crown Hts - Utica Av after our crews replaced rails at Nostrand Av.
6. Northbound 2 and 4 trains are holding in stations while our crews perform urgent track maintenance at Atlantic Av - Barclays Ctr.
7. Church Av-bound G trains are delayed while we request medical assistance for an injured passenger at Hoyt - Schermerhorn Sts.
8. Southbound D trains are delayed because of a slow-moving work train on the Manhattan Bridge.
9. Northbound N and Q trains have resumed local service from 34 St - Herald Sq to 57 St - 7 Av after a work train dropped off equipment along the local track. Reminder: Northbound 49 St station is being skipped during this time.
10. Expect longer wait times in northbound 4 trains after we removed from service a car that needed cleaning at Borough Hall.
11. Northbound 4 trains are delayed while we remove from service a train that needs cleaning at Grand Central - 42 St .
12. Northbound 2 and 5 trains are proceeding with delays after we removed a train that needs cleaning from service at Prospect Av.
13. Southbound 4 and 5 trains are proceeding with delays after NYPD removed a disruptive passenger from a train at Grand Central - 42 St.
14. Southbound C trains are delayed while we request NYPD assistance with a disruptive passenger at Broadway Jct.
15. Northbound A trains are delayed because of FDNY activity at 175 St.
16. 6 trains are running with delays in both directions while we work to correct a mechanical problem on a train at Brooklyn Bridge - City Hall.
17. Southbound D and N trains have resumed making express stops from Atlantic Av - Barclays Ctr to 36 St and 59 St in Brooklyn after NYPD and EMS responded to someone in need at Atlantic Av - Barclays Ctr.
18. Southbound F trains are delayed while NYPD responds to a disruptive passenger at Roosevelt Island.
19. 7 trains are delayed leaving and entering 34 St - Hudson Yds while we request NYPD and EMS assistance for someone at that station.
20. Northbound C trains are delayed while we request EMS assistance for someone in need at 168 St.
'''

In [84]:
((len(INPUTS)/4) / 20) * 67021

2199964.325

In [75]:
chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": BASE_PROMPT
        }
    ],
    model="gpt-4o-mini",
)

In [76]:
responses = chat_completion.choices[0].message.content.split('\n')
responses

['1. {issue: "Switch problem", station: "Briarwood"}',
 '2. {issue: "Cleaning / vandalism", station: "Bedford Av"}',
 '3. {issue: "Disruptive passenger", station: "168 St"}',
 '4. {issue: "Maintenance work", station: "Hunts Point Av"}',
 '5. {issue: "Rail problem", station: "Nostrand Av"}',
 '6. {issue: "Maintenance work", station: "Atlantic Av - Barclays Ctr"}',
 '7. {issue: "Medical emergency", station: "Hoyt - Schermerhorn Sts"}',
 '8. {issue: "Rail problem", station: "Unclear"}',
 '9. {issue: "Other", station: "Unclear"}',
 '10. {issue: "Cleaning / vandalism", station: "Borough Hall"}',
 '11. {issue: "Cleaning / vandalism", station: "Grand Central - 42 St"}',
 '12. {issue: "Cleaning / vandalism", station: "Prospect Av"}',
 '13. {issue: "Disruptive passenger", station: "Grand Central - 42 St"}',
 '14. {issue: "Disruptive passenger", station: "Broadway Jct"}',
 '15. {issue: "Medical emergency", station: "175 St"}',
 '16. {issue: "Unknown mechanical problem", station: "Brooklyn Bridge

1. Coney Island-bound F trains have resumed making local stops from Parsons Blvd to Kew Gardens - Union Tpke after our crews corrected a malfunctioning switch at Briarwood.
2. Canarsie-bound L trains are holding in stations while we remove a car in need of cleaning from service at Bedford Av.
3. Uptown A and C trains are delayed while NYPD responds to a disruptive passenger at 168 St.
4. Northbound 6 trains are delayed while our crews perform urgent track maintenance at Hunts Point Av.
5. Southbound 4 train service has resumed running local from Atlantic Av - Barclays Ctr to Crown Hts - Utica Av after our crews replaced rails at Nostrand Av.
6. Northbound 2 and 4 trains are holding in stations while our crews perform urgent track maintenance at Atlantic Av - Barclays Ctr.
7. Church Av-bound G trains are delayed while we request medical assistance for an injured passenger at Hoyt - Schermerhorn Sts.
8. Southbound D trains are delayed because of a slow-moving work train on the Manhattan Bridge.
9. Northbound N and Q trains have resumed local service from 34 St - Herald Sq to 57 St - 7 Av after a work train dropped off equipment along the local track. Reminder: Northbound 49 St station is being skipped during this time.
10. Expect longer wait times in northbound 4 trains after we removed from service a car that needed cleaning at Borough Hall.
11. Northbound 4 trains are delayed while we remove from service a train that needs cleaning at Grand Central - 42 St .
12. Northbound 2 and 5 trains are proceeding with delays after we removed a train that needs cleaning from service at Prospect Av.
13. Southbound 4 and 5 trains are proceeding with delays after NYPD removed a disruptive passenger from a train at Grand Central - 42 St.
14. Southbound C trains are delayed while we request NYPD assistance with a disruptive passenger at Broadway Jct.
15. Northbound A trains are delayed because of FDNY activity at 175 St.
16. 6 trains are running with delays in both directions while we work to correct a mechanical problem on a train at Brooklyn Bridge - City Hall.
17. Southbound D and N trains have resumed making express stops from Atlantic Av - Barclays Ctr to 36 St and 59 St in Brooklyn after NYPD and EMS responded to someone in need at Atlantic Av - Barclays Ctr.
18. Southbound F trains are delayed while NYPD responds to a disruptive passenger at Roosevelt Island.
19. 7 trains are delayed leaving and entering 34 St - Hudson Yds while we request NYPD and EMS assistance for someone at that station.
20. Northbound C trains are delayed while we request EMS assistance for someone in need at 168 St.
